from outlet.env import BASE_DIR, env, env_to_enum

EMAIL_HOST = env('EMAIL_HOST')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')