from outlet.env import BASE_DIR, env, env_to_enum


MODE = env('MODE')
MPESA_SANDBOX = env('MPESA_SANDBOX')
MPESA_USERNAME = env('MPESA_USERNAME')
MPESA_PASSWORD = env('MPESA_PASSWORD')
MPESA_BUSINESS_SHORT_CODE = env('MPESA_BUSINESS_SHORT_CODE')
MPESA_PASSKEY = env('MPESA_PASSKEY')
MPESA_CALLBACK = env('MPESA_CALLBACK')
MPESA_ACCESS_TOKEN_URL = env('MPESA_ACCESS_TOKEN_URL')
MPESA_LIPA_NA_MPESA_URL = env('MPESA_LIPA_NA_MPESA_URL')
NGROK_URL = env('NGROK_URL')
