# Generated by Django 4.0.2 on 2022-04-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_favourite_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
