# Generated by Django 4.0.2 on 2022-04-23 19:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('phone', models.CharField(max_length=256)),
                ('transaction_desc', models.CharField(max_length=256)),
                ('merchant_req_id', models.CharField(max_length=256)),
                ('checkout_req_id', models.CharField(max_length=256)),
                ('result_code', models.IntegerField()),
                ('result_desc', models.TextField()),
                ('receipt_number', models.CharField(max_length=256)),
                ('transaction_date', models.DateTimeField()),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_transactions', to='src.order')),
            ],
        ),
    ]
