# Generated by Django 4.0.2 on 2022-04-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_mpesatransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='receipt_number',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='result_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='result_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_date',
            field=models.DateTimeField(null=True),
        ),
    ]
